 export {FileInfoRoot as Root} from './FileInfoRoot' 
 export {FileInfoHeader as Header} from './FileInfoHeader'
 export {FileInfocontent as Content} from './FileInfoContent'
 export {FileInfoStatus as Status} from './FileInfoStatus'
 export {FileInfoProgressBarContainer as ProgressBarContainer} from './FileInfoProgressBarContainer'
 export {FileInfoProgressBar as ProgressBar} from './FileInfoProgressBar'
 export {FileInfoPercentage as Percentage} from './FileInfoPercentage'